---
name: pull-request
on:
  pull_request:
    branches: [main]

jobs:
  scan:
    name: Scan Code
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout Action
        uses: actions/checkout@v3

      # create sonarqube report
      # needs sonar-project.properties file in root
      - name: Sonar Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      # Fail if quality gate is red
      - uses: sonarsource/sonarqube-quality-gate-action@master
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  test:
    name: Test
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout Action
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
          cache: npm

      - name: Install dependencies, build and test
        run: |
          npm ci
          # building validation
          npm run build
          # test validation
          CI=true npm test --if-present
