---
name: pull-request
on:
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout Action
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
          cache: npm

      - name: Install dependencies, build and test
        run: |
          npm ci
          # building validation
          npm run build
          # test validation
          CI=true npm test --if-present
