---
name: angular-azure-static-web-apps-sonarqube
on:
  push:
    branches: [main]

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout Action
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
          cache: npm

      # create sonarqube report
      # needs sonar-project.properties file in root
      - name: Sonar Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      # Fail if quality gate is red
      - uses: sonarsource/sonarqube-quality-gate-action@master
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Install dependencies, build and test project
        run: |
          npm ci
          CI=true npm test --if-present -- \
          --watch=false \
          --browsers=ChromeHeadless
          npm run build
      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{secrets.AZURE_STATIC_WEB_APPS_API_TOKEN}}
          # repo_token: ${secrets.GITHUB_TOKEN}
          action: "upload"
          app_location: "dist"
          skip_app_build: true
