---
name: pull-request

on:
  pull_request:
    branches: [dev]

jobs:
  terraform:
    name: Terraform code validation
    runs-on: ubuntu-18.04
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout Action
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.5

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: terraform fmt
        run: terraform fmt -check

      - name: terraform validate
        run: |
          terraform init
          terraform validate

      - name: terraform plan
        run:
          terraform plan -var-file="envs/dev"

  scan:
    name: tfsec scan
    runs-on: ubuntu-18.04
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout Action
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install go
        uses: actions/setup-go@v3
        with:
          go-version: '^1.17.0'

      - name: Install tfsec
        run: go install github.com/aquasecurity/tfsec/cmd/tfsec@latest

      - name: Scan code
        run: tfsec .
